name: 'publish'

on:
  push:
    branches:
      - 'feature/*'

# This workflow will trigger on push to a 'feature/*/ branch
# It will create a new pull request targetting the main branch

jobs:
  create-pull-request:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          git-token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref }}
          title: "Merge ${{ github.ref_name }} into main"
          body: "Created by Github action via commit ${{ github.sha }}"
          draft: false
          delete-branch: true
          reviewers: mcarigs
