name: 'publish'

on:
  push:
    tags:
      - 'v*'

# This workflow will trigger on creation of a `v*/*` tag
# It will create/update a GitHub release, build the app, and upload the artifacts to the release.

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: '--bundles nsis'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Frontend Dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: 'MGS2 ASI Mod Config Editor v__VERSION__'
          releaseDraft: false
          prerelease: true
          args: ${{ matrix.args }}
