name: 'publish'

on:
  push:
    tags:
      - 'v-*'

# This workflow will trigger on each push to a `release/*` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: '--bundles nsis'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Frontend Dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: 'MGS2 ASI Mod Config Editor v__VERSION__'
          releaseBody: |
              - Download the latest release & launch the installer. When asked where to install the application, choose the `bin\scripts` folder where you have MGS2 installed.
                - For example: `C:\Program Files (x86)\GOG Galaxy\Games\Metal Gear Solid 2 Substance\bin\scripts`.
              - As a precaution, it's recommended to backup of your existing `.ini` files before using this application
          releaseDraft: false
          prerelease: true
          args: ${{ matrix.args }}
